---
abstract: 'A L<Data::Visitor> for creating Moose objects from blessed placeholders'
author:
  - 'Yuval Kogman <nothingmuch@woobling.org>'
  - 'Jonathan Rockway <jrockway@cpan.org>'
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  ok: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.011, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Blessed-Reconstruct
provides:
  MooseX::Blessed::Reconstruct:
    file: lib/MooseX/Blessed/Reconstruct.pm
    version: '1.01'
requires:
  Carp: '0'
  Class::MOP: '0.93'
  Data::Visitor: '0.21'
  Module::Runtime: '0'
  Moose: '1.05'
  Scalar::Util: '0'
  namespace::clean: '0'
resources:
  bugtracker: https://github.com/yanick/moosex-blessed-reconstruct/issues
  homepage: https://github.com/yanick/moosex-blessed-reconstruct
  repository: https://github.com/yanick/moosex-blessed-reconstruct.git
version: '1.01'
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.01
x_contributors:
  - 'E. Choroba <choroba@matfyz.cz>'
  - 'Jesse Luehrs <doy@tozt.net>'
x_serialization_backend: 'YAML::Tiny version 1.67'
